menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
search: true

widgets: 
#- tagcloud 
#- category
- recent_posts

excerpt_link: Read More

addthis:
  enable: false

fancybox: true

#google_analytics: UA-41590217-1

